@startuml

component App {
  [Controller]
  [Model]
  [View]
}

[Lanterna] <<library>>

Model --> View
Model <-- Controller


[View]

component Model {
  component GameLogic {
    [LevelBuilder]
    [UnitFactory]
    [ItemFactory]

    LevelBuilder o-- LevelBuilder
    LevelBuilder o-- UnitFactory
    UnitFactory o-- ItemFactory
  }
  component LevelLogic {
    [Judge]
    [Unit]
    [Item]
    [Strategy]

    Unit *- Strategy
    Unit *-- Item
  }
  [InventoryLogic]
  [State]

  GameLogic .. State
  LevelLogic .. State
  InventoryLogic .. State

}


Controller ...> Lanterna : use
View ...> Lanterna : use

@enduml