package ru.itmo.rogue.model.game.unit;

import ru.itmo.rogue.model.State;

public class Unit {
    protected int health;
    protected int strength;
    protected Item[] stash;
    protected int horizontalPos;
    protected int verticalPos;
    protected UnitStrategy strategy;

    public Action getAction(State state) {
        return strategy.getAction(this, state);
    }

    // TODO:
    //  Important: State.Delta is from outer package,
    //             I don't think it's good,
    //             Maybe change package structure?
    /**
     * @param x horizontal move
     * @param y vertical move
     * @return delta of the state generated by the change
     */
    public State.Delta move(int x, int y) {
        // TODO: Implement
        return null;
    }

    /**
     * @param change change in health, positive number increases health, negative - decreases
     * @return delta of the state generated by the change
     */
    public State.Delta health(int change) {
        // TODO: Implement
        return null;
    }


    public Item[] getStash() {
        return stash;
    }

    public int getHealth() {
        return health;
    }

    public int getStrength() {
        return strength;
    }

    public int getHorizontalPos() {
        return horizontalPos;
    }

    public int getVerticalPos() {
        return verticalPos;
    }

    public UnitStrategy getStrategy() {
        return strategy;
    }
}
